title:            Nashville Women Programmers
tagline:          A short tagline
description:      Describe your website.
#Swap out url when working locally to resolve base urls correctly
# url:              http://localhost:4000
url:              http://nashvillewomenprogrammers.com

# Owner/author information
owner:
  name:           Nashville Women Programmers
  avatar:         bio-photo.jpg
  bio:            "NWP is a group of women programmers that meet regularly to build a welcoming environment to learn and to grow diversity in the programming field. People of all backgrounds and skill levels are welcome to attend."
  email:          eliza@elizabrocksoftware.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook: groups/nashSTEAM/
  github: nashville-women-programmers
  meetup: NashvilleWomenProgrammers
  linkedin:
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /
  - title: Articles
    url: /articles
  - title: NWP Meetup Group
    url: http://www.meetup.com/NashvilleWomenProgrammers/
    external: true
  - title: NWP Google Group
    url: https://groups.google.com/forum/#!forum/nashville-women-programmers
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
